package com.itsorderkds.service

enum class SocketEvent(val raw: String) {
    ORDER_PENDING("ORDER_PENDING"),
    ORDER_CREATED("ORDER_CREATED"),
    ORDER_REMINDER("ORDER_REMINDER"),
    ORDER_CHANGE_STATUS("ORDER_CHANGE_STATUS"),
    ORDER_NEW("ORDER_NEW"),
    ORDER_PAID("ORDER_PAID"),
    ORDER_UPDATE("ORDER_UPDATE"),
    ORDER_PROCESSING("ORDER_PROCESSING"),
    ORDER_ACCEPTED("ORDER_ACCEPTED"),
    ORDER_CANCELLED("ORDER_CANCELLED"),
    ORDER_REJECTED("ORDER_REJECTED"),
    ORDER_OUT_FOR_DELIVERY("ORDER_OUT_FOR_DELIVERY"),
    ORDER_COMPLETED("ORDER_COMPLETED"),
    ORDER_NEW_COURIER("ORDER_NEW_COURIER"),
    ORDER_STATUS_ERROR("ORDER_STATUS_ERROR"),
    REJECT_ORDER_COURIER("REJECT_ORDER_COURIER"),
    ACCEPT_ORDER_COURIER("ACCEPT_ORDER_COURIER"),
    TRAS_COURIER_ORDER_NEW("TRAS_COURIER_ORDER_NEW"),
    OPEN_HOURS_UPDATED("OPEN_HOURS_UPDATED"),
    OPEN_HOURS_PAUSE_CLEARED("OPEN_HOURS_PAUSE_CLEARED"),
    OPEN_HOURS_PAUSE_SET("OPEN_HOURS_PAUSE_SET"),
    OPEN_HOURS_CREATED( "OPEN_HOURS_CREATED"),
    ORDER_SEND_TO_EXTERNAL_SUCCESS("ORDER_SEND_TO_EXTERNAL_SUCCESS"),
    ORDER_SEND_TO_EXTERNAL_FAILED("ORDER_SEND_TO_EXTERNAL_FAILED"),
    ORDER_SEND_TO_EXTERNAL_COURIER("ORDER_SEND_TO_EXTERNAL_COURIER");

    companion object {
        /** Zamienia tekst z socketa na odpowiadający mu enum. Zwraca null, gdy tekst nie pasuje. */
        fun fromRaw(raw: String): SocketEvent? =
            values().firstOrNull { it.raw == raw }
    }
}
